Добавляет адаптивные сетки крупным блокам
htmlacademy-adaptive/2315875-sedona-28 pull request #4
Opened 2023-04-11 21:20 UTC by oxxse

2023-04-13 15:43 UTC, vadimrahmanov requested changes
Сайт в целом выглядит сломаным.

Кстати, медиа выражения можно писать сразу в селекторе.
Например:

```
body {
  padding: 0;
  
  @media (min-width: @desktop-width) {
      padding: 20px;
  }
}
```

Я заметил у тебя очень много гридов. Такое чувство, что ты их хочешь использовать везде, где можно 😄  Не нужно этого делать. Гриды - не замена флексам. Где можно сделать на флексах, сделай на флексах, а где уже прям просятся гриды, то делай на гридах.

2023-04-13 15:43 UTC, vadimrahmanov commented on source/less/blocks/advantages.less
> +    grid-template-columns: 1fr 1fr 1fr;
В таких случаях можно использовать `repeat(3, 1fr)`

2023-04-13 15:43 UTC, vadimrahmanov commented on source/less/blocks/advantages.less
> +    grid-template-rows: repeat(4, 256px);
Устанавливать высоту для строк не очень хорошая практика, не стоит так делать т.к это делает фиксированную высоту

2023-04-13 15:43 UTC, vadimrahmanov commented on source/less/blocks/advantages.less
> +}
Этот блок уж очень перемудрён. Здесь бы я посоветовал сделать также как ты делала на первом курсе. Очень много лишних свойств и действий. В целом если что-то конкретно непонятно в гридах, то дай знать.

2023-04-14 08:57 UTC, vadimrahmanov requested changes
В идеале было бы избавиться от всех свойств `width` (исключение - декоративные элементы), так как флекс и грид позволяет это сделать.  Плюс паддинги.

`min-width` - в редких и действительно необходимых случаях.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/advantages.less
> +    width: 33.3%;
Тут можно блоку с текстом задать `flex: 1;` , а картинке `flex: 3;` например.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/advantages.less
> +    width: 33.3%;
Лучше` flex: 1`; здесь использовать

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/card.less
> +
Если это убрать, то ничего не меняется.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/filling-form.less
> +}
Здесь тоже перемудрено и усложнено, просто сделай какую-нибудь обёртку и сделай флексом или гридом. А то слишком много селекторов да и какие-то десятичные значения у свойств.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/filling-form.less
> +
Это нужно переделать.
Во-первых, всё не по макету.
Во-вторых, у тебя каша из свойств потому, что висят классы, которые вообще не нужны и из-за них нужно что-то мудрить и переписывать.

![Screenshot 2023-04-14 at 09 34 22](https://user-images.githubusercontent.com/53314530/231990907-c329b42c-ee01-414c-8ae7-b556a39b38eb.png)

Здесь не нужно ни width, ни margin

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-footer.less
> +  margin: 33px 82px;
Padding - внутренний отступ
Margin - внешний отступ, который отделяет элементы друг от друга.

Ты используешь `margin` там, где нужно `padding`. Это не только здесь, а в целом.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-footer.less
> +    min-width: @tablet-width;
Если этого не будет, то ничего не изменится.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-footer.less
> +    margin: 36px 60px;
margin вместо padding.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-footer.less
> +    margin: 36px 120px;
margin вместо padding.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/hotel-search.less
> +    margin: 38px 371px 49px 371px;
margin вместо padding.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-header.less
> +    left: 507px;
Ещё одно магическое число.

Чтобы отцентровать абсолютно спозиционированный элемент можно написать следующее:

```
left: 50%;
transform: translateX(-50%);
```

Если нужно что-либо отцентрировать по-вертикали, то:

```
top: 50%;
transform: translateY(-50%);
```

А если же и по-вертикали и по-горизонтали:

```
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
```

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-nav.less
> +    flex-direction: row;
`flex-direction: row;` нужно прописывать только в тех случаях, когда мы переходим из column в row. Здесь не тот случай.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-header.less
> +    min-width: @tablet-width;
Лишнее свойство.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-header.less
> +    min-width: @desktop-width;
Лишнее свойство.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-header.less
> +    left: 291px;
Написал об этом замечание выше.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-nav.less
> +    min-width: @desktop-width;
Лишнее свойство.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/main-header.less
>  }
Здесь никак не может быть `position: absolute;`

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/media.less
> +  }
Нужно переделать с помощью flex/grid.

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/review.less
> +    margin: 36px 166px 28px 166px;
margin вместо padding

2023-04-14 08:57 UTC, vadimrahmanov commented on source/less/blocks/review.less
> +    margin: 36px 382px 28px 382px;
margin вместо padding

2023-04-14 21:15 UTC, oxxse commented
Постаралась убрать min-width, где смогла придумать.. где не сработало с флексами/гридами и где position: absolute пришлось оставить. В футере тоже не выходило, без flex на body (для стики футера) все получается, а так никак не выходит без указания ширины. Ну и с textarea тоже. Где flex-grow не помог для того чтобы элемент занял всю ширину, взяла flex: 100%, не знаю, может так нельзя, но в гугле не нашла) ну и padding/margin переиграла. С модалками до конца не разобралась, в следующей домашке планирую доделать.

2023-04-16 19:48 UTC, vadimrahmanov requested changes

2023-04-16 19:48 UTC, vadimrahmanov commented on source/less/blocks/advantages.less
> +    min-width: 100%;
Зачем это свойство? Ведь оно же ничего не меняет

2023-04-16 19:48 UTC, vadimrahmanov commented on source/form.html
>        <nav class="main-header__nav main-nav">
При нажатии в любом месте на лого должно переводить на домашнюю страницу. Сейчас такое поведение лишь при нажатии на нижний хвостик.

2023-04-16 19:48 UTC, vadimrahmanov commented on source/less/blocks/advantages.less
> +    img {
у этого изображения имеется класс по-которому следует задавать стили

2023-04-16 19:48 UTC, vadimrahmanov commented on source/less/blocks/main-nav.less
> +  z-index: 1;
Это не должно быть абсолютно спозиционировано. Я писал про логотип. В шапке должен быть абсолютно спозиционирован только он.

2023-04-16 19:48 UTC, vadimrahmanov commented on source/less/blocks/modal.less
> +  }
марджины вместо паддингов.

2023-04-17 08:27 UTC, vadimrahmanov approved these changes
Я приму, но когда начнёшь делать микросетки я думаю и так многое поменяешь))

2023-04-17 08:27 UTC, vadimrahmanov commented on source/less/blocks/main-nav.less
> +    position: static;
Ну раз больше нету position: absolute; этого больше не надо)

2023-04-17 08:27 UTC, merged